version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: portfolio
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules